[tizen]
is_emulator = false
device_triple = "arm-linux-gnueabi"
sync_files = ["shared", "res", "tizen-manifest.xml"]

[tizen.device]
tizen_triple = "arm-linux-gnueabi"
security_profile = "default"

[tizen.emulator]
tizen_triple = "i586-linux-gnueabi"
security_profile = "default"

[tizen.target.arm-linux-gnueabi]
rust_triple = "arm-unknown-linux-gnueabi"

[tizen.target.i586-linux-gnueabi]
rust_triple = "i586-unknown-linux-gnu"
